version: '3.4'

services:
  weatherweb:
    image: ${DOCKER_REGISTRY-}weatherweb
    build:
      context: .
      dockerfile: weatherweb\Dockerfile

  weatherapi:
    image: ${DOCKER_REGISTRY-}weatherapi
    build:
      context: .
      dockerfile: weatherapi\Dockerfile

